preset_locations = ["workspace/presets/", "workspace", "package/presets/"]
batch_locations = ["workspace/batched_commands/", "workspace", "package/batched_commands/"]
bot_locations = ["workspace/robots/", "workspace", "package/robots/"]
code_locations = ["workspace/code/", "workspace", "package/robots/"]
config_locations = ["workspace", "package"]
device_locations = ["workspace/devices/", "package/devices/"]
theme_locations = ["workspace/assets/", "workspace", "package/assets"]
asset_locations = ["workspace/assets/", "workspace", "package/assets/"]
